"""initial migration

Revision ID: 0745fd3b1eaf
Revises: 
Create Date: 2025-11-24 21:50:08.396126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0745fd3b1eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('historico')
    op.drop_table('clinicas')
    op.drop_table('passeios')
    op.drop_table('vacinas')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('saude',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('pets_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['dono_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pets_ibfk_1'), 'users', ['dono_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('saude',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               existing_nullable=True)

    op.create_table('vacinas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('data_aplicacao', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('vacinas_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('passeios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), nullable=True),
    sa.Column('local', mysql.VARCHAR(collation='utf8mb4_general_ci', length=150), nullable=True),
    sa.Column('observacoes', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('passeios_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clinicas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historico',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_evento', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('historico_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('agendamentos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.Column('descricao', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinicas.id'], name=op.f('agendamentos_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('agendamentos_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
